#! /bin/sh
# chimage - updates a disk image
# Distributed with nexware, licensed under the MIT license
# See LICENSE

# Get and validate parameters
disk=$1
prefix=$2

if [ ! -f "$disk" ]
then
    echo "chimage: $disk doesn't exist"
    exit 1
fi

if [ ! -d "$prefix" ]
then
    echo "chimage: $prefix doesn't exist"
    exit 1
fi

# Get loop device and setup the device
loopdev=$(losetup -Pf --show $disk)
sleep 2

# Mount disk
mkdir fs
mount ${loopdev}p1 fs
sleep 1

# Copy data
cp -r $prefix/* fs/
sleep 1

# Unmount
umount fs
rm -r fs

# Delete loopback
losetup -d $loopdev
