#! /bin/sh
# image - creates a disk image
# Distributed with nexware, licensed under the MIT license
# See LICENSE

disktypes="mbr end"
disktype=
# Get the disk type
for type in $disktypes
do
    # Check if they equal
    if [ $type = $1 ] && [ "$type" != "end" ]
    then
        disktype=$1
        break
    elif [ "$type" = "end" ]
    then
        echo "image: Invalid disk type"
        exit 1
    fi
done

# Be sure that output file and image size are set
if [ -z "$2" ] || [ -z "$3" ]
then
    echo "image: Parameter not set"
    exit 1
fi

# Get output file
output=$2
# Convert size to bytes from mb
size=$(expr $3 \* 1024)
size=$(expr $size \* 1024)
# Now create and format it
dd if=/dev/zero of=$output bs=$size count=1

# Partition it
parted --script $output mklabel msdos mkpart p fat32 1 15M mkpart p ext2 16M ${3}M set 1 boot on

# First, get the loopback device using kpartx and awk
loopdev=$(kpartx -l $output | awk '{print $5; exit}' | awk -F '/' '{print $3}')
# Setup the partitions
kpartx -av $output
sleep 3
# Format boot partition
mkfs.vfat -F 16 -s 4 /dev/mapper/${loopdev}p1
sleep 1
# Format data partition
mkfs.ext2 /dev/mapper/${loopdev}p2
sleep 1
# Delete partitions
kpartx -d $output
